import logging
from typing import Any

import torch
from detectron2.config import configurable
from detectron2.data import MetadataCatalog
from detectron2.modeling import META_ARCH_REGISTRY
from detectron2.modeling.postprocessing import sem_seg_postprocess
from detectron2.utils.logger import log_first_n
from torch import device, einsum, nn, zeros
from torch.nn import functional as F

from .clip_adapter import MaskFormerClipAdapter, build_text_prompt
from .sam3_proposal import SAM3ProposalGenerator


@META_ARCH_REGISTRY.register()
class OVSAMSeg(nn.Module):
    """
    SAM3 をマスクプロポーザルに使った Open-Vocabulary Segmentation モデル。
    MaskFormer の代わりに SAM3 で高品質マスクを生成し、CLIP で領域分類する。
    """

    @configurable
    def __init__(
        self,
        *,
        sam3: SAM3ProposalGenerator,
        clip_adapter: MaskFormerClipAdapter,
        metadata: Any,
        pixel_mean: tuple[float, float, float],
        pixel_std: tuple[float, float, float],
    ) -> None:
        super().__init__()
        self.sam3 = sam3
        self.clip_adapter = clip_adapter
        self.metadata = metadata
        self.register_buffer("pixel_mean", torch.Tensor(pixel_mean).view(-1, 1, 1), False)
        self.register_buffer("pixel_std", torch.Tensor(pixel_std).view(-1, 1, 1), False)

    @classmethod
    def from_config(cls, cfg: Any) -> dict[str, Any]:
        text_templates = build_text_prompt(cfg.MODEL.CLIP_ADAPTER)

        clip_adapter = MaskFormerClipAdapter(
            cfg.MODEL.CLIP_ADAPTER.CLIP_MODEL_NAME,
            text_templates,
            mask_fill=cfg.MODEL.CLIP_ADAPTER.MASK_FILL,
            mask_expand_ratio=cfg.MODEL.CLIP_ADAPTER.MASK_EXPAND_RATIO,
            mask_thr=cfg.MODEL.CLIP_ADAPTER.MASK_THR,
            mask_matting=cfg.MODEL.CLIP_ADAPTER.MASK_MATTING,
            region_resized=cfg.MODEL.CLIP_ADAPTER.REGION_RESIZED,
            mask_prompt_depth=cfg.MODEL.CLIP_ADAPTER.MASK_PROMPT_DEPTH,
            mask_prompt_fwd=cfg.MODEL.CLIP_ADAPTER.MASK_PROMPT_FWD,
        )

        sam3 = SAM3ProposalGenerator(
            model_name=cfg.MODEL.SAM3.MODEL_NAME,
            mask_threshold=cfg.MODEL.SAM3.MASK_THRESHOLD,
            max_masks=cfg.MODEL.SAM3.MAX_MASKS,
        )

        return {
            "sam3": sam3,
            "clip_adapter": clip_adapter,
            "metadata": MetadataCatalog.get(cfg.DATASETS.TRAIN[0]),
            "pixel_mean": cfg.MODEL.PIXEL_MEAN,
            "pixel_std": cfg.MODEL.PIXEL_STD,
        }

    @property
    def device(self) -> device:
        return self.pixel_mean.device  # pyright: ignore[reportReturnType]

    def forward(self, batched_inputs: list[dict[str, Any]]) -> list[dict[str, torch.Tensor]]:
        class_names = self._get_class_names(batched_inputs)

        if len(class_names) == 0:
            log_first_n("WARNING", "No class names found for evaluation.")
            h, w = batched_inputs[0].get("height", 0), batched_inputs[0].get("width", 0)
            return [{"sem_seg": zeros(1, h, w, device=self.device)}]

        processed_results = []
        for input_per_image in batched_inputs:
            image = input_per_image["image"].to(self.device)
            h_aug, w_aug = image.shape[-2:]

            sam3_masks, _ = self.sam3(
                image,
                class_names,
                original_image_size=(h_aug, w_aug),
            )

            if sam3_masks.shape[0] == 0:
                log_first_n(logging.WARNING, "No masks generated by SAM3.")
                semseg = zeros(len(class_names), h_aug, w_aug, device=self.device)
            else:
                clip_cls, _, valid_flag = self.clip_adapter(image, class_names, sam3_masks, normalize=True)

                if clip_cls is None or clip_cls.shape[0] == 0:
                    semseg = zeros(len(class_names), h_aug, w_aug, device=self.device)
                else:
                    clip_cls = F.softmax(clip_cls[:, :-1], dim=-1)
                    valid_masks = sam3_masks[valid_flag].float()
                    semseg = einsum("mc,mhw->chw", clip_cls, valid_masks)

            height = input_per_image.get("height", h_aug)
            width = input_per_image.get("width", w_aug)
            semseg = sem_seg_postprocess(semseg, (h_aug, w_aug), height, width)

            processed_results.append({"sem_seg": semseg})

        return processed_results

    def _get_class_names(self, batched_inputs: list[dict[str, Any]]) -> list[str]:
        if "class_names" in batched_inputs[0]:
            return batched_inputs[0]["class_names"]
        dataset_name = batched_inputs[0].get("meta", {}).get("dataset_name", "")
        if dataset_name:
            return [c.strip() for c in MetadataCatalog.get(dataset_name).stuff_classes]
        return []
